### PR TITLE
Fixing Borders and Text Wrap

### PR DESCRIPTION
**Pull request by intfract**
## CSS 
- Fixed the design of post lists 
- Fixed buttons with theory 

## JS 
- Button names changed

### CODE REVIEW

**Comment by dotargz** [comment]
sir.... we need some of that css

**Comment by intfract** [comment]
Duplicate declarations overwrite one another and are not recommended. I am pretty sure the JS changes the attribute of the element rather than the CSS. CSS is used for styling and is connected to the style attribute. HTML element attributes will overwrite CSS declarations. It should work unless your app structure is different. 

[HTML Attribute vs CSS](https://stackoverflow.com/questions/3562296/whats-the-difference-between-the-html-width-height-attribute-and-the-css-widt)

**Comment by intfract** [comment]
More importantly, I should have kept the `display: none;` instead of `display: flex;` because I wasn't aware of its purpose.

**Comment by intfract** [comment]
Kynosocial's client is very friendly in terms of collaboration. I like the query router as well. The SPA makes it very easy for development. I can give you the repl if you want. The login and everything works normally. It's a JavaScript client after all.

**Comment by intfract** [comment]
DeepSource is having a spasm though because of the older JS.

**Comment by dotargz** [comment]
Does this work with the current themes system? If not, please add support for it, and please make sure that if you are making a large design change, that it is fully consistent across the entire website.

**Comment by dotargz** [comment]
I like the concept of this design... but it looks too subtle. It's hard for me to see what is part of a post and what is not. I really want kynosocial to be as easy to read as physically possible. It should feel like a book in its default form. No clutter. Defined borders and separation. Solid, Contrasting colors

**Comment by intfract** [comment]
Yes it works with the current theme system. The changes are global. I used the CSS variables from the themes. 
image

**Comment by intfract** [comment]
People would prefer having the usernames above like the comments section of the post. It prevents text-wrap and everything is properly left-aligned. **Long usernames text-wrap** while short usernames are center-aligned. Yes, it makes the post compact but it's bad design practice since long usernames become **unreadable**. I also increased the width of the workspace to `800px` in response to a post. Unfortunately, some of the things `futured_it` said were true. 

image

Despite his rude comments, we should interpret his feedback constructively. The new design does need improvements, but for now, it makes the cut for good practice. 
- Removed strokes and borders to reduce the harsh contrast 
- Removed the text shadows for readability 
- Positioned the text inside the container 
- Changed the post flex box to make longer usernames more readable. 
- Changed the buttons to reduce verb confusion and color confusion 

Of course, this is all my opinion. Maybe a vote on citrus would be a better way to make additional changes, but I promise you that this new design is a huge improvement from the older one.

**Comment by intfract** [comment]
I will ask my friend @nodexninja to talk on the discord about this because I am a bit busy with other stuff as well.

**Comment by intfract** [comment]
I have a few more things on my checklist though...
- [ ] Add post CSS 
- [ ] Fix text areas 
- [ ] Fix settings

**Comment by foxlldev** [comment]
PLEASE be more specific when you make a pull request

**Comment by foxlldev** [comment]
e.g. not "fix settings", instead "fix x about settings"

**Comment by intfract** [comment]
I added more detail.

**Pull request closed without merging**
